[tools]
node = "25"
pnpm = "latest"

[env]
_.path = ['{{config_root}}/node_modules/.bin']

[tasks.dev]
run = '''pnpm run --filter "@minies/${usage_app}" dev'''
usage = '''
arg "<app>" {
  choices "common" "home" "retail-calculators" "squarerizer"
}
'''
description = "Run the dev server for the selected app."
